version: "3.9"

services:
  fastapi:
    build: .
    container_name: miigaik_fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
